<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE KUNDE [
	<!ELEMENT KUNDE (KNR , KNAME, PLZ, ORT, STRASSE, BESTELLUNG)>
	<!ELEMENT KNR (#PCDATA)>
	<!ELEMENT KNAME (#PCDATA)>
	<!ELEMENT PLZ (#PCDATA)>
	<!ELEMENT ORT (#PCDATA)>
	<!ELEMENT STRASSE (#PCDATA)>
	<!ELEMENT BESTELLUNG (BSTNR, STATUS, RSUM, BPOS+)>
	<!ELEMENT BSTNR (#PCDATA)>
	<!ELEMENT STATUS (#PCDATA)>
	<!ELEMENT RSUM (#PCDATA)>
	<!ELEMENT BPOS (POSNR, MENGE, WERT, ARTIKEL)>
	<!ELEMENT POSNR (#PCDATA)>
	<!ELEMENT MENGE (#PCDATA)>
	<!ELEMENT WERT (#PCDATA)>
	<!ELEMENT ARTIKEL (ARTNR, ARTBEZ, MGE, PREIS, KUEHL)>
	<!ELEMENT ARTNR (#PCDATA)>
	<!ELEMENT ARTBEZ (#PCDATA)>
	<!ELEMENT MGE (#PCDATA)>
	<!ELEMENT PREIS (#PCDATA)>
	<!ELEMENT KUEHL (#PCDATA)>	
]>
<KUNDE>
	<KNR>1</KNR>
	<KNAME>Mueller</KNAME>
	<PLZ>50126</PLZ>
	<ORT>Bergheim</ORT>
	<STRASSE>Schoene Strasse 5</STRASSE>
		<BESTELLUNG>
			<BSTNR>2</BSTNR>
			<STATUS>2</STATUS>
			<RSUM>40.05</RSUM>
			<BPOS>
			
				<MENGE>2</MENGE>
				<POSNR>2</POSNR>					
				<WERT>5.78</WERT>
				<ARTIKEL>
				Stueck</MGE>
					<PREIS>1.49</PREIS>
					<KUEHL>NK</KUEHL>
				</ARTIKEL>
			</BPOS>
			<BPOS>
				<POSNR>7</POSNR>
				<MENGE>2</MENGE>
				<WERT>8.0</WERT>
				<ARTIKEL>
					<ARTNR>3</ARTNR>
					<ARTBEZ>Snickers</ARTBEZ>
					<MGE>Stueck</MGE>
					<PREIS>0.99</PREIS>
					<KUEHL>NK</KUEHL>
				</ARTIKEL>
			</BPOS>
			<BPOS>
				<POSNR>11</POSNR>
				<MENGE>4</MENGE>
				<WERT>8.36</WERT>
				<ARTIKEL>
					<ARTNR>4</ARTNR>
					<ARTBEZ>Fleisch</ARTBEZ>
					<MGE>Packung</MGE>
					<PREIS>3.49</PREIS>
					<KUEHL>TK</KUEHL>
				</ARTIKEL>
			</BPOS>
			<BPOS>
				<POSNR>15</POSNR>
				<MENGE>9</MENGE>
				<WERT>17.91</WERT>
				<ARTIKEL>
					<ARTNR>5</ARTNR>
					<ARTBEZ>Hundefutter</ARTBEZ>
					<MGE>Dose</MGE>
					<PREIS>1.49</PREIS>
					<KUEHL>NK</KUEHL>
				</ARTIKEL>
			</BPOS>
		</BESTELLUNG>
</KUNDE>